name: CI
on: [pull_request, push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
    - name: Setup package
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]
    - name: Run pytest
      run: pytest
